language: ruby

bundler_args: --without development

rvm:
  - 2.5
  - 2.6

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - rm config/database.yml
  - mv config/database.yml.template config/database.yml
  - cp env.test .env
  - mysql -e 'create database powerdns_test;'
  - psql -c 'create database powerdns_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:seed

script: "bundle exec rake spec"

matrix:
  allow_failures:
    - rvm: 2.6
    - env: DB=sqlite

sudo: false
