# https://edgeguides.rubyonrails.org/classic_to_zeitwerk_howto.html
Rails.autoloaders.main.inflector.inflect("aaaa" => "AAAA")
Rails.autoloaders.main.inflector.inflect("caa" => "CAA")
Rails.autoloaders.main.inflector.inflect("cname" => "CNAME")
Rails.autoloaders.main.inflector.inflect("loc" => "LOC")
Rails.autoloaders.main.inflector.inflect("mx" => "MX")
Rails.autoloaders.main.inflector.inflect("ns" => "NS")
Rails.autoloaders.main.inflector.inflect("ptr" => "PTR")
Rails.autoloaders.main.inflector.inflect("soa" => "SOA")
Rails.autoloaders.main.inflector.inflect("spf" => "SPF")
Rails.autoloaders.main.inflector.inflect("srv" => "SRV")
Rails.autoloaders.main.inflector.inflect("sshfp" => "SSHFP")
Rails.autoloaders.main.inflector.inflect("tlsa" => "TLSA")
Rails.autoloaders.main.inflector.inflect("txt" => "TXT")
